version: '3'

services:
  project_db:
    image: mysql:8.0
    container_name: project_db
    restart: unless-stopped
    ports:
      - 9100:3306
    env_file: .env
    environment:
      - MYSQL_DATABASE=$MYSQL_DATABASE
    volumes:
      - ./dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network

  project_wordpress:
    depends_on:
      - project_db
    image: wordpress:5.7.2-fpm-alpine
    container_name: project_wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=project_db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=$MYSQL_DATABASE
      - WORDPRESS_TABLE_PREFIX=mio_
    volumes:
      - ./proyecto:/var/www/html
    networks:
      - app-network

  project_webserver:
    depends_on:
      - project_wordpress
    image: nginx:1.15.12-alpine
    container_name: project_webserver
    restart: unless-stopped
    ports:
      - "8100:80"
    volumes:
      - ./proyecto:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
